### ISSUE TITLE
Why do u choose Spring vault

### ISSUE THREAD

**Issue by HelloTo4x** [ivangfr/springboot-vault-examples#2]
Hi, i am reading ur project, why do you use Spring vault for storing key, encrypt instead of other libraries, can you tell me your purpose, the pros and cons of using Vault,thank u

**Comment by ivangfr** [comment]
Hi @HelloTo4x I've already had to answer a similar question before related to Keycloak? Why are you asking all these questions? Some project you are working on? If yes, I'd be happy to help. However, I believe you creating issues on all my projects is not the right way to go. Connected with me on LinkedIn and I can try to answer all your question. Best regards!

**Comment by ivangfr** [comment]
My LinkedIn is on my GitHub profile.
